### ISSUE TITLE
NSFW判断问题等

### ISSUE THREAD

**Issue by sunbeams001** [my-telegram-bots/Pixiv_bot#1]
你好，感谢开发，挺好用的，我之前也在做一个类似工具，提几个小问题
1. NSFW区分问题，有些作品没有被正确处理，例如 88516433 ，x_restrict = 2，sanity_level=6，建议使用 sanity_level 联合判断
2. GIF 问题，似乎帧率是固定的？当单作品 ugoira 数据中单帧持续时间不一致时会有这个问题，例如 48964367

**Comment by makeding** [comment]
1. 看上去 x_restrict == 2 是直接 R18G 了，~~在写 NSFW 功能的时候没浏览过~~ 等下发个 commit 修
2. 帧率取决于 ffmpeg 心情，在一个视频里面应该是固定的，然后时间轴是使用 mp4fpsmod 调过了的，应该没有什么问题 // 或者我肉眼看不出网站上和 bot 转换后的区别

**Comment by sunbeams001** [comment]
3. tags 功能似乎无效？
解释一下，GIF 的meta信息里有写每帧的持续时间，然后这个值对于每一帧是可能不同的，我的例子中可以详细看看眨眼附近，如果在网页上播放是流畅的，直接转换就会有问题，按道理是应该根据meta信息构造可变帧率，或者按照不同持续时间分段合成再拼接，我不是很熟悉ffmpeg，不知道能不能做到这种

**Comment by makeding** [comment]
3. tags 功能与 sc(single caption) 冲突，如果 +sc 了 那么就不会显示 +tags，另外也和自定义格式有关系，如果自定义回复格式里面不包含 %tags% 字段，那么也不会有任何 tags 出现（默认开启 tags 的功能还在咕咕咕，代码已经写成💩山了，不知道用什么方案好点）


网站屏幕录制版本和转换成 mp4 版本对比后，我能直接感受到的就是 结尾应该还有个 3 秒的停顿没了（正在找解决方案

**Comment by sunbeams001** [comment]
看看这个行不，我没试过，看起来差不多
https://trac.ffmpeg.org/wiki/Slideshow
concat demuxer 这段

**Comment by makeding** [comment]
https://user-images.githubusercontent.com/6511667/120096359-991f0b80-c15d-11eb-9ede-64708d78c99f.mp4

最左边是在 pixiv 官网渲染然后屏幕录制的，然后中间是修复版本，右边是 bot 原始版本
屏幕录制的有点延迟，不同步了，好难剪，感觉基本没啥问题了？

**Comment by sunbeams001** [comment]
OK，bot原始版本我这差的有点多，tg上预览看中间眨眼大概卡住2秒，导出mp4单独打开就没事了

**Comment by makeding** [comment]
大概修了 https://github.com/my-telegram-bots/Pixiv_bot/tree/513f40f02d04fddb267bff540bce715e2cab3164
