### ISSUE TITLE
illust's tags missing in custom message format configuration

### ISSUE THREAD

**Issue by rodnm** [my-telegram-bots/Pixiv_bot#6]
Hello, I'm trying to use the bot message format configuration following the [guide](https://pixiv-bot.pages.dev/s) but my only issue is the bot is not writing tags in message.

My custom format is like this:
```
%• Source\: [%url%](%url%)%
%• Title\: [%title%](%url%)%
%• Artist\: [%author_name%](%author_url%)% \(%author_id%\)
%• ID\: %id%%
%• Tags\: %tags%%
\#pixiv %NSFW|#NSFW
%p%
```
I will show an example of the issue with this [illustration](https://www.pixiv.net/artworks/67953985).

The preview on the [guide](https://pixiv-bot.pages.dev/s) works fine:
![Screenshot_2022-03-29_154600_msedge](https://user-images.githubusercontent.com/61637386/160704168-aa187feb-15b6-4e18-b81e-8d4d66e38d12.png)

But in Telegram looks like this:
![Screenshot_2022-03-29_154824_Telegram](https://user-images.githubusercontent.com/61637386/160704424-b43e993d-caed-46c5-9dde-f0c4de777867.png)

Side note: In preview the ID of the [illustration](https://www.pixiv.net/artworks/67953985) is missing but it works anyway in bot.

**Comment by makeding** [comment]
Tags will be shown with `/s +tags` configuration.

<img width="488" alt="image" src="https://user-images.githubusercontent.com/6511667/160754293-73def162-9ae7-499b-9098-30aa40a54cdd.png">

**Comment by rodnm** [comment]
Nice, it works! Thanks
